/*************************************************
 * LIS
 * @file types.js
 * @author Sasidharan // on 08/10/2020
 * @copyright © 2020 LIS. All rights reserved.
 *************************************************/
export const ACTION_TYPES = {
	SET_AUTH_TOKENS: 'SET_AUTH_TOKENS',
	SET_BOOKING_DETAILS: 'SET_BOOKING_DETAILS',
	SET_BOOKING_DETAILS_SEARCH: 'SET_BOOKING_DETAILS_SEARCH',
	SET_BOOKING_STATUS_SEARCH: 'SET_BOOKING_STATUS_SEARCH',
	SET_PATIENT_FILTER_SEARCH: 'SET_PATIENT_FILTER_SEARCH',
	SET_TRACKING_LIST: 'SET_TRACKING_LIST',
	SET_TEST_LIST_DETAILS: 'SET_TEST_LIST_DETAILS',
	SET_PHLEBOTOMIST_DETAILS: 'SET_PHLEBOTOMIST_DETAILS',
	SET_BOOKING_TYPE_DETAILS: 'SET_BOOKING_TYPE_DETAILS',
	SET_BOOKING_FILTER_DETAILS: 'SET_BOOKING_FILTER_DETAILS',
	SET_BOOKING_DETAILED: 'SET_BOOKING_DETAILED',
	SET_TEST_DETAILS: 'SET_TEST_DETAILS',
	SET_GENDER: 'SET_GENDER',
	RESET_ALL: 'RESET_ALL',
	SET_ADDRESS_TYPE: 'SET_ADDRESS_TYPE',
	SET_PATIENT_RELATIONSHIP: 'SET_PATIENT_RELATIONSHIP',
	SET_PATIENT: 'SET_PATIENT',
	SET_PATIENT_LIST: 'SET_PATIENT_LIST',
	SET_USER_ADDRESS_LIST: 'SET_USER_ADDRESS_LIST',
	SET_PROMOTION: 'SET_PROMOTION',
	APPLY_PROMOTION: 'APPLY_PROMOTION',
	BOOKING_UPDATE: 'BOOKING_UPDATE',
	SET_GROUP_TEST: 'SET_GROUP_TEST',
	SET_GROUP_TEST_LIST: 'SET_GROUP_TEST_LIST',
	SET_SOS_FILTER_LIST: 'SET_SOS_FILTER_LIST',
	SET_SOS_LIST: 'SET_SOS_LIST',
	SET_BOOKING_DETAILS_FILTER_DATA: 'SET_BOOKING_DETAILS_FILTER_DATA',
	SET_NOTIFICATION: 'SET_NOTIFICATION',
	SET_NOTIFICATION_COUNT: 'SET_NOTIFICATION_COUNT',
	SET_REVIEW_TYPE: 'SET_REVIEW_TYPE',
	SET_RATING_ACTION_TYPE: 'SET_RATING_ACTION_TYPE',
	SET_RATING_BY_STAR: 'SET_RATING_BY_STAR',
	SET_RATED_BY: 'SET_RATED_BY',
	SET_RATING: 'SET_RATING',
	OTP_SEND_PATIENT: 'OTP_SEND_PATIENT',
}
